pgmo:
    horizon: 15.0
    output_mesh_resolution: 0.02
    graph_compression_method: 1  # voxblox
    full_compression_method: 2  # voxel clearing
    robot_id: 0
    d_graph_resolution: 2.5
    voxblox_queue_size: 1
mesh_queue_size: 10
active_objects_horizon_s: 10.0
active_index_horizon_m: 10.0
enable_active_mesh_pub: false
enable_segmented_mesh_pub: false
min_object_vertices: 15
min_cluster_size: 15
cluster_tolerance: 0.25
prune_mesh_indices: true
mesh_ns: ""
visualize_dsg_lcd: true
prune_mesh_indices: true
