---
- {sub_id: 0, super_id: 0}
- {sub_id: 1, super_id: 1}
- {sub_id: 2, super_id: 2}
- {sub_id: 2, super_id: 20}
- {sub_id: 3, super_id: 22}
- {sub_id: 4, super_id: 8}
- {sub_id: 5, super_id: 9}
- {sub_id: 5, super_id: 13}
- {sub_id: 5, super_id: 16}
- {sub_id: 6, super_id: 12}
- {sub_id: 7, super_id: 15}
- {sub_id: 7, super_id: 10}
- {sub_id: 8, super_id: 40}
- {sub_id: 9, super_id: 4}
- {sub_id: 9, super_id: 18}
- {sub_id: 10, super_id: 3}
- {sub_id: 10, super_id: 17}
- {sub_id: 10, super_id: 29}
- {sub_id: 10, super_id: 37}
- {sub_id: 10, super_id: 24}
- {sub_id: 10, super_id: 32}
- {sub_id: 11, super_id: 7}
- {sub_id: 11, super_id: 14}
- {sub_id: 12, super_id: 5}
- {sub_id: 13, super_id: 11}
- {sub_id: 13, super_id: 19}
- {sub_id: 13, super_id: 30}
- {sub_id: 14, super_id: 6}
- {sub_id: 15, super_id: 35}
- {sub_id: 16, super_id: 28}
- {sub_id: 16, super_id: 33}
- {sub_id: 16, super_id: 34}
- {sub_id: 16, super_id: 36}
- {sub_id: 17, super_id: 23}
- {sub_id: 17, super_id: 25}
- {sub_id: 17, super_id: 26}
- {sub_id: 18, super_id: 27}
- {sub_id: 18, super_id: 21}
- {sub_id: 19, super_id: 38}
- {sub_id: 19, super_id: 39}
- {sub_id: 20, super_id: 31}
